language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install flake8
  - python setup.py install
  - pip install coveralls
script:
  - coverage run setup.py test
  - flake8 .
after_success:
  coveralls
notifications:
  email:
    - ci-notify@openlabs.co.in

env:
  - FACEBOOK_APP_ID=152288694978641 FACEBOOK_APP_SECRET=1f166ff67503972ceb44e2b01548db20
